spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:db-postgresql-fra1-66773-do-user-23232317-0.k.db.ondigitalocean.com}:${DB_PORT:25060}/${DB_NAME:w8realty}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update   # ??? ????????; ?? ????? ????? ????????
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: ${PORT:8080}

security:
  jwt:
    secret: ${JWT_SECRET:bWloYWlsZWJsYW5jaGtlZGZyZXRoeXJ0dG9waW1qeWh0bm9pcGpnZmhiaW9tbnBmZ25vbWlwa2ZnaG5samtmYmdua2pmZ2huams}
    issuer: ${JWT_ISSUER:realty-api}
    ttl-minutes: ${JWT_TTL_MINUTES:43200}

logging:
  level:
    org.springframework.security: DEBUG

yandex:
  feed:
    storageDir: ${YANDEX_FEED_DIR:/var/app/feeds/yandex}   # директория на диске
    baseUrl: ${YANDEX_FEED_BASE_URL:localhost:8080/feeds/yandex}   # базовый публичный URL

auth:
  username: ${AUTH_USERNAME:admin}
  password: ${AUTH_PASSWORD:admin}